// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Accept the server certificate
func GetAcceptRemoteCertificate(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "lxd:acceptRemoteCertificate")
}
func GetAddress(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:address")
}

// The directory to look for existing LXD configuration. default = $HOME/.config/lxc
func GetConfigDir(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:configDir")
}
func GetGenerateClientCertificates(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "lxd:generateClientCertificates")
}
func GetLxdRemotes(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "lxd:lxdRemotes")
	if err == nil {
		return v
	}
	return getEnvOrDefault(pulumi.StringArray{}, parseEnvStringArray, "LXD_REMOTE").(pulumi.StringArray)
}
func GetPort(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:port")
}

// How often to poll during state changes (default 10s)
func GetRefreshInterval(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:refreshInterval")
}
func GetRemote(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:remote")
}
func GetRemotePassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:remotePassword")
}
func GetScheme(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:scheme")
}
