// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LxdRemotes struct {
	Address  *string `pulumi:"address"`
	Default  *bool   `pulumi:"default"`
	Name     string  `pulumi:"name"`
	Password *string `pulumi:"password"`
	Port     *string `pulumi:"port"`
	Scheme   *string `pulumi:"scheme"`
}

// LxdRemotesInput is an input type that accepts LxdRemotesArgs and LxdRemotesOutput values.
// You can construct a concrete instance of `LxdRemotesInput` via:
//
//          LxdRemotesArgs{...}
type LxdRemotesInput interface {
	pulumi.Input

	ToLxdRemotesOutput() LxdRemotesOutput
	ToLxdRemotesOutputWithContext(context.Context) LxdRemotesOutput
}

type LxdRemotesArgs struct {
	Address  pulumi.StringPtrInput `pulumi:"address"`
	Default  pulumi.BoolPtrInput   `pulumi:"default"`
	Name     pulumi.StringInput    `pulumi:"name"`
	Password pulumi.StringPtrInput `pulumi:"password"`
	Port     pulumi.StringPtrInput `pulumi:"port"`
	Scheme   pulumi.StringPtrInput `pulumi:"scheme"`
}

func (LxdRemotesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LxdRemotes)(nil)).Elem()
}

func (i LxdRemotesArgs) ToLxdRemotesOutput() LxdRemotesOutput {
	return i.ToLxdRemotesOutputWithContext(context.Background())
}

func (i LxdRemotesArgs) ToLxdRemotesOutputWithContext(ctx context.Context) LxdRemotesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LxdRemotesOutput)
}

// LxdRemotesArrayInput is an input type that accepts LxdRemotesArray and LxdRemotesArrayOutput values.
// You can construct a concrete instance of `LxdRemotesArrayInput` via:
//
//          LxdRemotesArray{ LxdRemotesArgs{...} }
type LxdRemotesArrayInput interface {
	pulumi.Input

	ToLxdRemotesArrayOutput() LxdRemotesArrayOutput
	ToLxdRemotesArrayOutputWithContext(context.Context) LxdRemotesArrayOutput
}

type LxdRemotesArray []LxdRemotesInput

func (LxdRemotesArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LxdRemotes)(nil)).Elem()
}

func (i LxdRemotesArray) ToLxdRemotesArrayOutput() LxdRemotesArrayOutput {
	return i.ToLxdRemotesArrayOutputWithContext(context.Background())
}

func (i LxdRemotesArray) ToLxdRemotesArrayOutputWithContext(ctx context.Context) LxdRemotesArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LxdRemotesArrayOutput)
}

type LxdRemotesOutput struct{ *pulumi.OutputState }

func (LxdRemotesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LxdRemotes)(nil)).Elem()
}

func (o LxdRemotesOutput) ToLxdRemotesOutput() LxdRemotesOutput {
	return o
}

func (o LxdRemotesOutput) ToLxdRemotesOutputWithContext(ctx context.Context) LxdRemotesOutput {
	return o
}

func (o LxdRemotesOutput) Address() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LxdRemotes) *string { return v.Address }).(pulumi.StringPtrOutput)
}

func (o LxdRemotesOutput) Default() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LxdRemotes) *bool { return v.Default }).(pulumi.BoolPtrOutput)
}

func (o LxdRemotesOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LxdRemotes) string { return v.Name }).(pulumi.StringOutput)
}

func (o LxdRemotesOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LxdRemotes) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o LxdRemotesOutput) Port() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LxdRemotes) *string { return v.Port }).(pulumi.StringPtrOutput)
}

func (o LxdRemotesOutput) Scheme() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LxdRemotes) *string { return v.Scheme }).(pulumi.StringPtrOutput)
}

type LxdRemotesArrayOutput struct{ *pulumi.OutputState }

func (LxdRemotesArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LxdRemotes)(nil)).Elem()
}

func (o LxdRemotesArrayOutput) ToLxdRemotesArrayOutput() LxdRemotesArrayOutput {
	return o
}

func (o LxdRemotesArrayOutput) ToLxdRemotesArrayOutputWithContext(ctx context.Context) LxdRemotesArrayOutput {
	return o
}

func (o LxdRemotesArrayOutput) Index(i pulumi.IntInput) LxdRemotesOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LxdRemotes {
		return vs[0].([]LxdRemotes)[vs[1].(int)]
	}).(LxdRemotesOutput)
}

func init() {
	pulumi.RegisterOutputType(LxdRemotesOutput{})
	pulumi.RegisterOutputType(LxdRemotesArrayOutput{})
}
