# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

__all__ = [
    'lxd_remote',
    'accept_remote_certificate',
    'address',
    'config_dir',
    'generate_client_certificates',
    'port',
    'refresh_interval',
    'remote',
    'remote_password',
    'scheme',
]

__config__ = pulumi.Config('lxd')

lxd_remote = __config__.get('LXDRemote')

accept_remote_certificate = __config__.get('acceptRemoteCertificate')
"""
Accept the server certificate
"""

address = __config__.get('address')

config_dir = __config__.get('configDir')
"""
The directory to look for existing LXD configuration. default = $HOME/.config/lxc
"""

generate_client_certificates = __config__.get('generateClientCertificates')

port = __config__.get('port')

refresh_interval = __config__.get('refreshInterval')
"""
How often to poll during state changes (default 10s)
"""

remote = __config__.get('remote')

remote_password = __config__.get('remotePassword')

scheme = __config__.get('scheme')

