# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .cached_image import *
from .container import *
from .container_file import *
from .network import *
from .profile import *
from .provider import *
from .publish_image import *
from .snapshot import *
from .storage_pool import *
from .volume import *
from .volume_container_attach import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_lxd.config as config
else:
    config = _utilities.lazy_import('pulumi_lxd.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "lxd",
  "mod": "index/containerFile",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/containerFile:ContainerFile": "ContainerFile"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/profile",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/profile:Profile": "Profile"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/storagePool",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/storagePool:StoragePool": "StoragePool"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/container",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/container:Container": "Container"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/network",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/network:Network": "Network"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/publishImage",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/publishImage:PublishImage": "PublishImage"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/snapshot",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/snapshot:Snapshot": "Snapshot"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/volume",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/volume:Volume": "Volume"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/volumeContainerAttach",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/volumeContainerAttach:VolumeContainerAttach": "VolumeContainerAttach"
  }
 },
 {
  "pkg": "lxd",
  "mod": "index/cachedImage",
  "fqn": "pulumi_lxd",
  "classes": {
   "lxd:index/cachedImage:CachedImage": "CachedImage"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "lxd",
  "token": "pulumi:providers:lxd",
  "fqn": "pulumi_lxd",
  "class": "Provider"
 }
]
"""
)
