// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Lxd.Outputs
{

    [OutputType]
    public sealed class ContainerDevice
    {
        public readonly string Name;
        public readonly ImmutableDictionary<string, object> Properties;
        public readonly string Type;

        [OutputConstructor]
        private ContainerDevice(
            string name,

            ImmutableDictionary<string, object> properties,

            string type)
        {
            Name = name;
            Properties = properties;
            Type = type;
        }
    }
}
