// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Lxd.Outputs
{

    [OutputType]
    public sealed class ProviderLxdRemote
    {
        public readonly string? Address;
        public readonly bool? Default;
        public readonly string Name;
        public readonly string? Password;
        public readonly string? Port;
        public readonly string? Scheme;

        [OutputConstructor]
        private ProviderLxdRemote(
            string? address,

            bool? @default,

            string name,

            string? password,

            string? port,

            string? scheme)
        {
            Address = address;
            Default = @default;
            Name = name;
            Password = password;
            Port = port;
            Scheme = scheme;
        }
    }
}
