// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package lxd

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "lxd:index/cachedImage:CachedImage":
		r = &CachedImage{}
	case "lxd:index/container:Container":
		r = &Container{}
	case "lxd:index/containerFile:ContainerFile":
		r = &ContainerFile{}
	case "lxd:index/network:Network":
		r = &Network{}
	case "lxd:index/profile:Profile":
		r = &Profile{}
	case "lxd:index/publishImage:PublishImage":
		r = &PublishImage{}
	case "lxd:index/snapshot:Snapshot":
		r = &Snapshot{}
	case "lxd:index/storagePool:StoragePool":
		r = &StoragePool{}
	case "lxd:index/volume:Volume":
		r = &Volume{}
	case "lxd:index/volumeContainerAttach:VolumeContainerAttach":
		r = &VolumeContainerAttach{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:lxd" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"lxd",
		"index/cachedImage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/container",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/containerFile",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/profile",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/publishImage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/snapshot",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/storagePool",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/volume",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"lxd",
		"index/volumeContainerAttach",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"lxd",
		&pkg{version},
	)
}
