// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface ContainerDevice {
    name: pulumi.Input<string>;
    properties: pulumi.Input<{[key: string]: any}>;
    type: pulumi.Input<string>;
}

export interface ContainerFile {
    content?: pulumi.Input<string>;
    createDirectories?: pulumi.Input<boolean>;
    gid?: pulumi.Input<number>;
    mode?: pulumi.Input<string>;
    source?: pulumi.Input<string>;
    targetFile: pulumi.Input<string>;
    uid?: pulumi.Input<number>;
}

export interface ProfileDevice {
    name: pulumi.Input<string>;
    properties: pulumi.Input<{[key: string]: any}>;
    type: pulumi.Input<string>;
}

export interface ProviderLxdRemote {
    address?: pulumi.Input<string>;
    default?: pulumi.Input<boolean>;
    name: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    port?: pulumi.Input<string>;
    scheme?: pulumi.Input<string>;
}
export namespace config {
}
