// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CachedImage extends pulumi.CustomResource {
    /**
     * Get an existing CachedImage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CachedImageState, opts?: pulumi.CustomResourceOptions): CachedImage {
        return new CachedImage(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lxd:index/cachedImage:CachedImage';

    /**
     * Returns true if the given object is an instance of CachedImage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CachedImage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CachedImage.__pulumiType;
    }

    public readonly aliases!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly architecture!: pulumi.Output<string>;
    public /*out*/ readonly copiedAliases!: pulumi.Output<string[]>;
    public readonly copyAliases!: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly createdAt!: pulumi.Output<number>;
    public /*out*/ readonly fingerprint!: pulumi.Output<string>;
    public readonly remote!: pulumi.Output<string | undefined>;
    public readonly sourceImage!: pulumi.Output<string>;
    public readonly sourceRemote!: pulumi.Output<string>;

    /**
     * Create a CachedImage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CachedImageArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CachedImageArgs | CachedImageState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CachedImageState | undefined;
            inputs["aliases"] = state ? state.aliases : undefined;
            inputs["architecture"] = state ? state.architecture : undefined;
            inputs["copiedAliases"] = state ? state.copiedAliases : undefined;
            inputs["copyAliases"] = state ? state.copyAliases : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["fingerprint"] = state ? state.fingerprint : undefined;
            inputs["remote"] = state ? state.remote : undefined;
            inputs["sourceImage"] = state ? state.sourceImage : undefined;
            inputs["sourceRemote"] = state ? state.sourceRemote : undefined;
        } else {
            const args = argsOrState as CachedImageArgs | undefined;
            if ((!args || args.sourceImage === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sourceImage'");
            }
            if ((!args || args.sourceRemote === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sourceRemote'");
            }
            inputs["aliases"] = args ? args.aliases : undefined;
            inputs["copyAliases"] = args ? args.copyAliases : undefined;
            inputs["remote"] = args ? args.remote : undefined;
            inputs["sourceImage"] = args ? args.sourceImage : undefined;
            inputs["sourceRemote"] = args ? args.sourceRemote : undefined;
            inputs["architecture"] = undefined /*out*/;
            inputs["copiedAliases"] = undefined /*out*/;
            inputs["createdAt"] = undefined /*out*/;
            inputs["fingerprint"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(CachedImage.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CachedImage resources.
 */
export interface CachedImageState {
    readonly aliases?: pulumi.Input<pulumi.Input<string>[]>;
    readonly architecture?: pulumi.Input<string>;
    readonly copiedAliases?: pulumi.Input<pulumi.Input<string>[]>;
    readonly copyAliases?: pulumi.Input<boolean>;
    readonly createdAt?: pulumi.Input<number>;
    readonly fingerprint?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
    readonly sourceImage?: pulumi.Input<string>;
    readonly sourceRemote?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CachedImage resource.
 */
export interface CachedImageArgs {
    readonly aliases?: pulumi.Input<pulumi.Input<string>[]>;
    readonly copyAliases?: pulumi.Input<boolean>;
    readonly remote?: pulumi.Input<string>;
    readonly sourceImage: pulumi.Input<string>;
    readonly sourceRemote: pulumi.Input<string>;
}
