// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Container extends pulumi.CustomResource {
    /**
     * Get an existing Container resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ContainerState, opts?: pulumi.CustomResourceOptions): Container {
        return new Container(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lxd:index/container:Container';

    /**
     * Returns true if the given object is an instance of Container.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Container {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Container.__pulumiType;
    }

    public readonly config!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly devices!: pulumi.Output<outputs.ContainerDevice[] | undefined>;
    public readonly ephemeral!: pulumi.Output<boolean | undefined>;
    public readonly files!: pulumi.Output<outputs.ContainerFile[] | undefined>;
    public readonly image!: pulumi.Output<string>;
    public /*out*/ readonly ipAddress!: pulumi.Output<string>;
    public /*out*/ readonly ipv4Address!: pulumi.Output<string>;
    public /*out*/ readonly ipv6Address!: pulumi.Output<string>;
    public readonly limits!: pulumi.Output<{[key: string]: any} | undefined>;
    public /*out*/ readonly macAddress!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    /**
     * @deprecated Use a config setting of security.privileged=1 instead
     */
    public readonly privileged!: pulumi.Output<boolean | undefined>;
    public readonly profiles!: pulumi.Output<string[]>;
    public readonly remote!: pulumi.Output<string | undefined>;
    public readonly startContainer!: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly status!: pulumi.Output<string>;
    public readonly target!: pulumi.Output<string>;
    public readonly type!: pulumi.Output<string>;
    public readonly waitForNetwork!: pulumi.Output<boolean | undefined>;

    /**
     * Create a Container resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ContainerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ContainerArgs | ContainerState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ContainerState | undefined;
            inputs["config"] = state ? state.config : undefined;
            inputs["devices"] = state ? state.devices : undefined;
            inputs["ephemeral"] = state ? state.ephemeral : undefined;
            inputs["files"] = state ? state.files : undefined;
            inputs["image"] = state ? state.image : undefined;
            inputs["ipAddress"] = state ? state.ipAddress : undefined;
            inputs["ipv4Address"] = state ? state.ipv4Address : undefined;
            inputs["ipv6Address"] = state ? state.ipv6Address : undefined;
            inputs["limits"] = state ? state.limits : undefined;
            inputs["macAddress"] = state ? state.macAddress : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["privileged"] = state ? state.privileged : undefined;
            inputs["profiles"] = state ? state.profiles : undefined;
            inputs["remote"] = state ? state.remote : undefined;
            inputs["startContainer"] = state ? state.startContainer : undefined;
            inputs["status"] = state ? state.status : undefined;
            inputs["target"] = state ? state.target : undefined;
            inputs["type"] = state ? state.type : undefined;
            inputs["waitForNetwork"] = state ? state.waitForNetwork : undefined;
        } else {
            const args = argsOrState as ContainerArgs | undefined;
            if ((!args || args.image === undefined) && !opts.urn) {
                throw new Error("Missing required property 'image'");
            }
            inputs["config"] = args ? args.config : undefined;
            inputs["devices"] = args ? args.devices : undefined;
            inputs["ephemeral"] = args ? args.ephemeral : undefined;
            inputs["files"] = args ? args.files : undefined;
            inputs["image"] = args ? args.image : undefined;
            inputs["limits"] = args ? args.limits : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["privileged"] = args ? args.privileged : undefined;
            inputs["profiles"] = args ? args.profiles : undefined;
            inputs["remote"] = args ? args.remote : undefined;
            inputs["startContainer"] = args ? args.startContainer : undefined;
            inputs["target"] = args ? args.target : undefined;
            inputs["type"] = args ? args.type : undefined;
            inputs["waitForNetwork"] = args ? args.waitForNetwork : undefined;
            inputs["ipAddress"] = undefined /*out*/;
            inputs["ipv4Address"] = undefined /*out*/;
            inputs["ipv6Address"] = undefined /*out*/;
            inputs["macAddress"] = undefined /*out*/;
            inputs["status"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Container.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Container resources.
 */
export interface ContainerState {
    readonly config?: pulumi.Input<{[key: string]: any}>;
    readonly devices?: pulumi.Input<pulumi.Input<inputs.ContainerDevice>[]>;
    readonly ephemeral?: pulumi.Input<boolean>;
    readonly files?: pulumi.Input<pulumi.Input<inputs.ContainerFile>[]>;
    readonly image?: pulumi.Input<string>;
    readonly ipAddress?: pulumi.Input<string>;
    readonly ipv4Address?: pulumi.Input<string>;
    readonly ipv6Address?: pulumi.Input<string>;
    readonly limits?: pulumi.Input<{[key: string]: any}>;
    readonly macAddress?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    /**
     * @deprecated Use a config setting of security.privileged=1 instead
     */
    readonly privileged?: pulumi.Input<boolean>;
    readonly profiles?: pulumi.Input<pulumi.Input<string>[]>;
    readonly remote?: pulumi.Input<string>;
    readonly startContainer?: pulumi.Input<boolean>;
    readonly status?: pulumi.Input<string>;
    readonly target?: pulumi.Input<string>;
    readonly type?: pulumi.Input<string>;
    readonly waitForNetwork?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Container resource.
 */
export interface ContainerArgs {
    readonly config?: pulumi.Input<{[key: string]: any}>;
    readonly devices?: pulumi.Input<pulumi.Input<inputs.ContainerDevice>[]>;
    readonly ephemeral?: pulumi.Input<boolean>;
    readonly files?: pulumi.Input<pulumi.Input<inputs.ContainerFile>[]>;
    readonly image: pulumi.Input<string>;
    readonly limits?: pulumi.Input<{[key: string]: any}>;
    readonly name?: pulumi.Input<string>;
    /**
     * @deprecated Use a config setting of security.privileged=1 instead
     */
    readonly privileged?: pulumi.Input<boolean>;
    readonly profiles?: pulumi.Input<pulumi.Input<string>[]>;
    readonly remote?: pulumi.Input<string>;
    readonly startContainer?: pulumi.Input<boolean>;
    readonly target?: pulumi.Input<string>;
    readonly type?: pulumi.Input<string>;
    readonly waitForNetwork?: pulumi.Input<boolean>;
}
