// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Profile extends pulumi.CustomResource {
    /**
     * Get an existing Profile resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProfileState, opts?: pulumi.CustomResourceOptions): Profile {
        return new Profile(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lxd:index/profile:Profile';

    /**
     * Returns true if the given object is an instance of Profile.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Profile {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Profile.__pulumiType;
    }

    public readonly config!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly devices!: pulumi.Output<outputs.ProfileDevice[] | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly remote!: pulumi.Output<string | undefined>;

    /**
     * Create a Profile resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProfileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProfileArgs | ProfileState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProfileState | undefined;
            inputs["config"] = state ? state.config : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["devices"] = state ? state.devices : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["remote"] = state ? state.remote : undefined;
        } else {
            const args = argsOrState as ProfileArgs | undefined;
            inputs["config"] = args ? args.config : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["devices"] = args ? args.devices : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["remote"] = args ? args.remote : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Profile.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Profile resources.
 */
export interface ProfileState {
    readonly config?: pulumi.Input<{[key: string]: any}>;
    readonly description?: pulumi.Input<string>;
    readonly devices?: pulumi.Input<pulumi.Input<inputs.ProfileDevice>[]>;
    readonly name?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Profile resource.
 */
export interface ProfileArgs {
    readonly config?: pulumi.Input<{[key: string]: any}>;
    readonly description?: pulumi.Input<string>;
    readonly devices?: pulumi.Input<pulumi.Input<inputs.ProfileDevice>[]>;
    readonly name?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
}
