// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Snapshot extends pulumi.CustomResource {
    /**
     * Get an existing Snapshot resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SnapshotState, opts?: pulumi.CustomResourceOptions): Snapshot {
        return new Snapshot(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lxd:index/snapshot:Snapshot';

    /**
     * Returns true if the given object is an instance of Snapshot.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Snapshot {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Snapshot.__pulumiType;
    }

    public readonly containerName!: pulumi.Output<string>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * @deprecated Use created_at instead
     */
    public /*out*/ readonly creationDate!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly remote!: pulumi.Output<string | undefined>;
    public readonly stateful!: pulumi.Output<boolean | undefined>;

    /**
     * Create a Snapshot resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SnapshotArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SnapshotArgs | SnapshotState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SnapshotState | undefined;
            inputs["containerName"] = state ? state.containerName : undefined;
            inputs["createdAt"] = state ? state.createdAt : undefined;
            inputs["creationDate"] = state ? state.creationDate : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["remote"] = state ? state.remote : undefined;
            inputs["stateful"] = state ? state.stateful : undefined;
        } else {
            const args = argsOrState as SnapshotArgs | undefined;
            if ((!args || args.containerName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'containerName'");
            }
            inputs["containerName"] = args ? args.containerName : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["remote"] = args ? args.remote : undefined;
            inputs["stateful"] = args ? args.stateful : undefined;
            inputs["createdAt"] = undefined /*out*/;
            inputs["creationDate"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Snapshot.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Snapshot resources.
 */
export interface SnapshotState {
    readonly containerName?: pulumi.Input<string>;
    readonly createdAt?: pulumi.Input<string>;
    /**
     * @deprecated Use created_at instead
     */
    readonly creationDate?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
    readonly stateful?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Snapshot resource.
 */
export interface SnapshotArgs {
    readonly containerName: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
    readonly stateful?: pulumi.Input<boolean>;
}
