// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StoragePool extends pulumi.CustomResource {
    /**
     * Get an existing StoragePool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StoragePoolState, opts?: pulumi.CustomResourceOptions): StoragePool {
        return new StoragePool(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lxd:index/storagePool:StoragePool';

    /**
     * Returns true if the given object is an instance of StoragePool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StoragePool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StoragePool.__pulumiType;
    }

    public readonly config!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly driver!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly remote!: pulumi.Output<string | undefined>;
    public readonly target!: pulumi.Output<string | undefined>;

    /**
     * Create a StoragePool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StoragePoolArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StoragePoolArgs | StoragePoolState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StoragePoolState | undefined;
            inputs["config"] = state ? state.config : undefined;
            inputs["driver"] = state ? state.driver : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["remote"] = state ? state.remote : undefined;
            inputs["target"] = state ? state.target : undefined;
        } else {
            const args = argsOrState as StoragePoolArgs | undefined;
            if ((!args || args.driver === undefined) && !opts.urn) {
                throw new Error("Missing required property 'driver'");
            }
            inputs["config"] = args ? args.config : undefined;
            inputs["driver"] = args ? args.driver : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["remote"] = args ? args.remote : undefined;
            inputs["target"] = args ? args.target : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(StoragePool.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering StoragePool resources.
 */
export interface StoragePoolState {
    readonly config?: pulumi.Input<{[key: string]: any}>;
    readonly driver?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
    readonly target?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StoragePool resource.
 */
export interface StoragePoolArgs {
    readonly config?: pulumi.Input<{[key: string]: any}>;
    readonly driver: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly remote?: pulumi.Input<string>;
    readonly target?: pulumi.Input<string>;
}
